name: C/C++ CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build --config Release -j2
      env:
        MAKEFLAGS: "-j2"
    - name: ls
      run: cd build && ls -l
    - name: test
      run: cd build && ctest -j2
    - name: ls
      run: cd build && ls -l
    - name: Upload ubuntu zip
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-build
        path: build/hello

  build-windows:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2016, macOS-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build --config Release -j2
      env:
        MAKEFLAGS: "-j2"
    - name: ls
      run: cd build && dir
    - name: test
      run: cd build && ctest -j2 
    - name: ls
      run: cd build && dir
    - name: Upload windows zip
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: build/Release/hello.exe
    - name: Upload macos zip
      uses: actions/upload-artifact@v2
      with:
        name: macOS-build
        path: build/hello
