name: Build, test and upload

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build --config Release -j2
    - name: test
      run: cd build && ctest -j2
    - name: Upload zip
      uses: actions/upload-artifact@v2
      with:
        name: ubuntu-build
        path: build/hello

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build --config Release -j2
    - name: test
      run: cd build && ctest -j2
    - name: Upload zip
      uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: build/hello
        
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir build && cd build && cmake ..
    - name: build
      run: cmake --build build --config Release -j2
    - name: test
      run: cd build && ctest -j2
    - name: Upload zip
      uses: actions/upload-artifact@v2
      with:
        name: macos-build
        path: build/hello
